Traceback (most recent call last):
  File "C:\Users\SS&AL\AppData\Roaming\Python\Python39\site-packages\graphviz\backend\execute.py", line 81, in run_check
    proc = subprocess.run(cmd, **kwargs)
  File "E:\conda3\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "E:\conda3\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "E:\conda3\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "C:\Programs\SpectrometerLearner\vanilla_train.py", line 295, in <module>
    make_dot(scores.mean(), params=dict(model.named_parameters())).render("rnn_torchviz", format="png")
  File "C:\Users\SS&AL\AppData\Roaming\Python\Python39\site-packages\graphviz\_tools.py", line 171, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\SS&AL\AppData\Roaming\Python\Python39\site-packages\graphviz\rendering.py", line 122, in render
    rendered = self._render(*args, **kwargs)
  File "C:\Users\SS&AL\AppData\Roaming\Python\Python39\site-packages\graphviz\_tools.py", line 171, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\SS&AL\AppData\Roaming\Python\Python39\site-packages\graphviz\backend\rendering.py", line 324, in render
    execute.run_check(cmd,
  File "C:\Users\SS&AL\AppData\Roaming\Python\Python39\site-packages\graphviz\backend\execute.py", line 84, in run_check
    raise ExecutableNotFound(cmd) from e
graphviz.backend.execute.ExecutableNotFound: failed to execute WindowsPath('dot'), make sure the Graphviz executables are on your systems' PATH
torch.Size([64, 3695])